version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/App
hooks:
    ApplicationStop:
      - location: codedeploy_scripts/application_stop.sh
        timeout: 300
        runas: ubuntu
    BeforeInstall:
       - location: codedeploy_scripts/before_install.sh
         timeout: 300
         runas: ubuntu
    ApplicationStart:
      - location: codedeploy_scripts/application_start.sh
        timeout: 300
        runas: ubuntu


